// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace apiNet8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250423055859_Tesaaq1")]
    partial class Tesaaq1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressModel", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            CountryId = 1,
                            ProvinceId = 1
                        },
                        new
                        {
                            AddressId = 2,
                            CountryId = 2,
                            ProvinceId = 2
                        });
                });

            modelBuilder.Entity("BusinessTypeModel", b =>
                {
                    b.Property<int>("busiTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("busiTypeID"));

                    b.Property<decimal?>("RegisteredCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("busiTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("busiTypeDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("busiTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("busiTypeID");

                    b.ToTable("BusinessTypes");

                    b.HasData(
                        new
                        {
                            busiTypeID = 1,
                            busiTypeCode = "RT",
                            busiTypeDes = "Retail Business Type Description",
                            busiTypeName = "Retail"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.CountryModel", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "Japan"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.CreditInfoModel", b =>
                {
                    b.Property<int>("CreditInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CreditInfoId"));

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedPurchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TimeRequired")
                        .HasColumnType("int");

                    b.HasKey("CreditInfoId");

                    b.ToTable("CreditInfo");

                    b.HasData(
                        new
                        {
                            CreditInfoId = 1,
                            CreditLimit = 100000.00m,
                            EstimatedPurchase = 50000.00m,
                            TimeRequired = 12
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.CustomerModel", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("BusinessTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("CreditInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("CustSignId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneralId")
                        .HasColumnType("int");

                    b.Property<int>("shipping_id")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("BusinessTypeId");

                    b.HasIndex("CreditInfoId");

                    b.HasIndex("CustSignId");

                    b.HasIndex("GeneralId");

                    b.HasIndex("shipping_id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            BusinessTypeId = 1,
                            CreditInfoId = 1,
                            CustSignId = 1,
                            CustomerName = "John Doe",
                            GeneralId = 1,
                            shipping_id = 1
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.CustomerSignModel", b =>
                {
                    b.Property<int>("CustSignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustSignId"));

                    b.Property<string>("CustSignFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("CustSignId");

                    b.ToTable("CustomerSign");

                    b.HasData(
                        new
                        {
                            CustSignId = 1,
                            CustSignFirstName = "John",
                            CustomerId = 0
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.GeneralModel", b =>
                {
                    b.Property<int>("general_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("general_id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("generalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("general_id");

                    b.HasIndex("AddressId");

                    b.ToTable("Generals");

                    b.HasData(
                        new
                        {
                            general_id = 1,
                            AddressId = 1,
                            generalName = "General A"
                        },
                        new
                        {
                            general_id = 2,
                            AddressId = 2,
                            generalName = "General B"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            CountryId = 1,
                            ProvinceName = "Bangkok"
                        },
                        new
                        {
                            ProvinceId = 2,
                            CountryId = 2,
                            ProvinceName = "Tokyo"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.ShippingModel", b =>
                {
                    b.Property<int>("shipping_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipping_id"));

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("subDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shipping_id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Shippings");

                    b.HasData(
                        new
                        {
                            shipping_id = 1,
                            ProvinceId = 1,
                            subDistrict = "บางรัก"
                        },
                        new
                        {
                            shipping_id = 2,
                            ProvinceId = 2,
                            subDistrict = "ห้วยขวาง"
                        });
                });

            modelBuilder.Entity("AddressModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.ProvinceModel", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ModelTest.Controllers.CustomerModel", b =>
                {
                    b.HasOne("BusinessTypeModel", "BusinessType")
                        .WithMany()
                        .HasForeignKey("BusinessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.CreditInfoModel", "CreditInfo")
                        .WithMany()
                        .HasForeignKey("CreditInfoId");

                    b.HasOne("ModelTest.Controllers.CustomerSignModel", "CustomerSigns")
                        .WithMany()
                        .HasForeignKey("CustSignId");

                    b.HasOne("ModelTest.Controllers.GeneralModel", "General")
                        .WithMany()
                        .HasForeignKey("GeneralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.ShippingModel", "Shipping")
                        .WithMany()
                        .HasForeignKey("shipping_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessType");

                    b.Navigation("CreditInfo");

                    b.Navigation("CustomerSigns");

                    b.Navigation("General");

                    b.Navigation("Shipping");
                });

            modelBuilder.Entity("ModelTest.Controllers.GeneralModel", b =>
                {
                    b.HasOne("AddressModel", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ModelTest.Controllers.ShippingModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.ProvinceModel", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ModelTest.Controllers.CountryModel", b =>
                {
                    b.Navigation("Provinces");
                });
#pragma warning restore 612, 618
        }
    }
}
