// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace apiNet8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421075325_Test2")]
    partial class Test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelTest.Controllers.AddressModel", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryModelCountryId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CountryModelCountryId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            CountryId = 1,
                            ProvinceId = 1,
                            Street = "123 ถนนสีลม",
                            ZipCode = "10500"
                        },
                        new
                        {
                            AddressId = 2,
                            CountryId = 1,
                            ProvinceId = 2,
                            Street = "456 ถ.สุเทพ",
                            ZipCode = "50200"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.AmphureModel", b =>
                {
                    b.Property<int>("AmphureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmphureId"));

                    b.Property<string>("AmphureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("AmphureId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("AmphureModel");

                    b.HasData(
                        new
                        {
                            AmphureId = 1,
                            AmphureName = "เขตบางรัก",
                            ProvinceId = 1
                        },
                        new
                        {
                            AmphureId = 2,
                            AmphureName = "อำเภอเมืองเชียงใหม่",
                            ProvinceId = 2
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.CountryModel", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("CountryModel");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "Thailand"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.CustomerModel", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneralId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("GeneralId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "ลูกค้า A",
                            GeneralId = 1
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "ลูกค้า B",
                            GeneralId = 2
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.GeneralModel", b =>
                {
                    b.Property<int>("general_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("general_id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("generalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("general_id");

                    b.HasIndex("AddressId");

                    b.ToTable("GeneralModel");

                    b.HasData(
                        new
                        {
                            general_id = 1,
                            AddressId = 1,
                            generalName = "นายสมชาย"
                        },
                        new
                        {
                            general_id = 2,
                            AddressId = 2,
                            generalName = "นางสาวดารา"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.GeographyModel", b =>
                {
                    b.Property<int>("GeographyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeographyId"));

                    b.Property<string>("GeographyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeographyId");

                    b.ToTable("Geography");

                    b.HasData(
                        new
                        {
                            GeographyId = 1,
                            GeographyName = "ภาคกลาง"
                        },
                        new
                        {
                            GeographyId = 2,
                            GeographyName = "ภาคเหนือ"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("GeographyId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GeographyId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            CountryId = 1,
                            GeographyId = 1,
                            ProvinceName = "กรุงเทพมหานคร"
                        },
                        new
                        {
                            ProvinceId = 2,
                            CountryId = 1,
                            GeographyId = 2,
                            ProvinceName = "เชียงใหม่"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.TambonModel", b =>
                {
                    b.Property<int>("TambonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TambonId"));

                    b.Property<int>("AmphureId")
                        .HasColumnType("int");

                    b.Property<string>("TambonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TambonId");

                    b.HasIndex("AmphureId");

                    b.ToTable("TambonModel");

                    b.HasData(
                        new
                        {
                            TambonId = 1,
                            AmphureId = 1,
                            TambonName = "สีลม"
                        },
                        new
                        {
                            TambonId = 2,
                            AmphureId = 2,
                            TambonName = "สุเทพ"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.AddressModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.CountryModel", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CountryModelCountryId");

                    b.HasOne("ModelTest.Controllers.ProvinceModel", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ModelTest.Controllers.AmphureModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.ProvinceModel", "Province")
                        .WithMany("Amphures")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ModelTest.Controllers.CustomerModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.GeneralModel", "General")
                        .WithMany()
                        .HasForeignKey("GeneralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("General");
                });

            modelBuilder.Entity("ModelTest.Controllers.GeneralModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.AddressModel", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.GeographyModel", "Geography")
                        .WithMany()
                        .HasForeignKey("GeographyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Geography");
                });

            modelBuilder.Entity("ModelTest.Controllers.TambonModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.AmphureModel", "Amphure")
                        .WithMany("Tambons")
                        .HasForeignKey("AmphureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amphure");
                });

            modelBuilder.Entity("ModelTest.Controllers.AmphureModel", b =>
                {
                    b.Navigation("Tambons");
                });

            modelBuilder.Entity("ModelTest.Controllers.CountryModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.Navigation("Amphures");
                });
#pragma warning restore 612, 618
        }
    }
}
