// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace apiNet8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250415214700_XX3")]
    partial class XX3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModelTest.Controllers.AddressModel", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            ProvinceId = 1,
                            Street = "123 Sukhumvit",
                            ZipCode = "10110"
                        },
                        new
                        {
                            AddressId = 2,
                            ProvinceId = 2,
                            Street = "456 Nimman",
                            ZipCode = "50000"
                        },
                        new
                        {
                            AddressId = 3,
                            ProvinceId = 3,
                            Street = "789 Shibuya",
                            ZipCode = "150-0002"
                        },
                        new
                        {
                            AddressId = 4,
                            ProvinceId = 5,
                            Street = "101 Manhattan",
                            ZipCode = "10001"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.BusinessTypeModel", b =>
                {
                    b.Property<int>("busiTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("busiTypeID"));

                    b.Property<decimal?>("RegisteredCapital")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("date");

                    b.Property<string>("busiTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("busiTypeDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("busiTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("busiTypeID");

                    b.ToTable("BusinessType");

                    b.HasData(
                        new
                        {
                            busiTypeID = 1,
                            RegisteredCapital = 1000000.00m,
                            RegistrationDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            busiTypeCode = "RET",
                            busiTypeDes = "ธุรกิจค้าปลีกทั่วไป",
                            busiTypeName = "ค้าปลีก"
                        },
                        new
                        {
                            busiTypeID = 2,
                            RegisteredCapital = 5000000.00m,
                            RegistrationDate = new DateTime(2011, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            busiTypeCode = "WHL",
                            busiTypeDes = "ธุรกิจค้าส่งสินค้า",
                            busiTypeName = "ค้าส่ง"
                        },
                        new
                        {
                            busiTypeID = 3,
                            RegisteredCapital = 15000000.00m,
                            RegistrationDate = new DateTime(2015, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            busiTypeCode = "MFG",
                            busiTypeDes = "โรงงานผลิตสินค้าทั่วไป",
                            busiTypeName = "การผลิต"
                        },
                        new
                        {
                            busiTypeID = 4,
                            RegisteredCapital = 2000000.00m,
                            RegistrationDate = new DateTime(2018, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            busiTypeCode = "SRV",
                            busiTypeDes = "บริษัทให้บริการทั่วไป",
                            busiTypeName = "บริการ"
                        },
                        new
                        {
                            busiTypeID = 5,
                            RegistrationDate = new DateTime(2005, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            busiTypeCode = "GOV",
                            busiTypeDes = "องค์กรภาครัฐ",
                            busiTypeName = "หน่วยงานราชการ"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.CompanyModel", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("company_id"));

                    b.Property<string>("companyAddr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("company_id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("ModelTest.Controllers.CountryModel", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Thailand"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Japan"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "United States"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.GeographyModel", b =>
                {
                    b.Property<int>("GeographyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeographyId"));

                    b.Property<string>("GeographyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeographyId");

                    b.ToTable("GeographyModel");

                    b.HasData(
                        new
                        {
                            GeographyId = 1,
                            GeographyName = "ภาคเหนือ"
                        },
                        new
                        {
                            GeographyId = 2,
                            GeographyName = "ภาคกลาง"
                        },
                        new
                        {
                            GeographyId = 3,
                            GeographyName = "ภาคตะวันออกเฉียงเหนือ"
                        },
                        new
                        {
                            GeographyId = 4,
                            GeographyName = "ภาคใต้"
                        },
                        new
                        {
                            GeographyId = 5,
                            GeographyName = "ภาคตะวันตก"
                        },
                        new
                        {
                            GeographyId = 6,
                            GeographyName = "ภาคตะวันออก"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.IndustryType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("InduTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InduTypeDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InduTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("IndustryType");
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("GeographyId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GeographyId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            CountryId = 1,
                            GeographyId = 2,
                            ProvinceName = "Bangkok"
                        },
                        new
                        {
                            ProvinceId = 2,
                            CountryId = 1,
                            GeographyId = 1,
                            ProvinceName = "Chiang Mai"
                        },
                        new
                        {
                            ProvinceId = 3,
                            CountryId = 2,
                            GeographyId = 2,
                            ProvinceName = "Tokyo"
                        },
                        new
                        {
                            ProvinceId = 4,
                            CountryId = 2,
                            GeographyId = 2,
                            ProvinceName = "Osaka"
                        },
                        new
                        {
                            ProvinceId = 5,
                            CountryId = 3,
                            GeographyId = 2,
                            ProvinceName = "California"
                        },
                        new
                        {
                            ProvinceId = 6,
                            CountryId = 3,
                            GeographyId = 2,
                            ProvinceName = "New York"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.SaleOrgModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("saleOrgCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saleOrgDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saleOrgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SaleOrg");
                });

            modelBuilder.Entity("ModelTest.Controllers.ShippingModel", b =>
                {
                    b.Property<int>("shipping_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipping_id"));

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("subDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shipping_id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Shippings");

                    b.HasData(
                        new
                        {
                            shipping_id = 1,
                            ProvinceId = 1,
                            subDistrict = "Wattana"
                        },
                        new
                        {
                            shipping_id = 2,
                            ProvinceId = 3,
                            subDistrict = "Shibuya"
                        },
                        new
                        {
                            shipping_id = 3,
                            ProvinceId = 5,
                            subDistrict = "Brooklyn"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.ThaiProvince", b =>
                {
                    b.Property<int>("ThaiProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThaiProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("GeographyId")
                        .HasColumnType("int");

                    b.Property<string>("ThaiProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThaiProvinceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GeographyId");

                    b.ToTable("ThaiProvinces");

                    b.HasData(
                        new
                        {
                            ThaiProvinceId = 1,
                            CountryId = 1,
                            GeographyId = 2,
                            ThaiProvinceName = "Bangkok"
                        },
                        new
                        {
                            ThaiProvinceId = 2,
                            CountryId = 1,
                            GeographyId = 1,
                            ThaiProvinceName = "Chiang Mai"
                        },
                        new
                        {
                            ThaiProvinceId = 3,
                            CountryId = 1,
                            GeographyId = 1,
                            ThaiProvinceName = "Chiang Rai"
                        },
                        new
                        {
                            ThaiProvinceId = 4,
                            CountryId = 1,
                            GeographyId = 4,
                            ThaiProvinceName = "Phuket"
                        },
                        new
                        {
                            ThaiProvinceId = 5,
                            CountryId = 1,
                            GeographyId = 3,
                            ThaiProvinceName = "Khon Kaen"
                        },
                        new
                        {
                            ThaiProvinceId = 6,
                            CountryId = 1,
                            GeographyId = 3,
                            ThaiProvinceName = "Nakhon Ratchasima"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.accountGroupModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("accGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accGroupDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("accountGroup");
                });

            modelBuilder.Entity("ModelTest.Controllers.shopTypeModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("InduTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("shopType");
                });

            modelBuilder.Entity("ModelTest.Controllers.AddressModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.ProvinceModel", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.GeographyModel", "Geography")
                        .WithMany("Provinces")
                        .HasForeignKey("GeographyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Geography");
                });

            modelBuilder.Entity("ModelTest.Controllers.ShippingModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.ProvinceModel", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ModelTest.Controllers.ThaiProvince", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.GeographyModel", "Geography")
                        .WithMany("ThaiProvinces")
                        .HasForeignKey("GeographyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Geography");
                });

            modelBuilder.Entity("ModelTest.Controllers.GeographyModel", b =>
                {
                    b.Navigation("Provinces");

                    b.Navigation("ThaiProvinces");
                });
#pragma warning restore 612, 618
        }
    }
}
