// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace apiNet8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250418083949_XX12")]
    partial class XX12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessTypeDto", b =>
                {
                    b.Property<int>("busiTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("busiTypeID"));

                    b.Property<decimal?>("RegisteredCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("busiTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("busiTypeDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("busiTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("busiTypeID");

                    b.ToTable("BusinessType");
                });

            modelBuilder.Entity("CompanyModel", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("company_id"));

                    b.Property<string>("companyAddr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("company_id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("IndustryType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("InduTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InduTypeDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InduTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("IndustryType");
                });

            modelBuilder.Entity("ModelTest.Controllers.AddressModel", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThaiProvinceId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("ThaiProvinceId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            CountryId = 1,
                            Street = "123 ถนนราชดำเนิน",
                            ThaiProvinceId = 2
                        },
                        new
                        {
                            AddressId = 2,
                            CountryId = 2,
                            ProvinceId = 1,
                            Street = "456 Sunset Blvd"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.CountryModel", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "ประเทศไทย"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "สหรัฐอเมริกา"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.GeneralModel", b =>
                {
                    b.Property<int>("general_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("general_id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("generalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("general_id");

                    b.HasIndex("AddressId");

                    b.ToTable("GeneralModel");

                    b.HasData(
                        new
                        {
                            general_id = 1,
                            AddressId = 1,
                            generalName = "John Doe"
                        },
                        new
                        {
                            general_id = 2,
                            AddressId = 2,
                            generalName = "Jane Smith"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.GeographyModel", b =>
                {
                    b.Property<int>("GeographyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeographyId"));

                    b.Property<string>("GeographyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GeographyId");

                    b.ToTable("GeographyModel");

                    b.HasData(
                        new
                        {
                            GeographyId = 1,
                            GeographyName = "ภาคเหนือ"
                        },
                        new
                        {
                            GeographyId = 2,
                            GeographyName = "ภาคกลาง"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("GeographyId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GeographyId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            CountryId = 2,
                            GeographyId = 2,
                            ProvinceName = "California"
                        },
                        new
                        {
                            ProvinceId = 2,
                            CountryId = 2,
                            GeographyId = 2,
                            ProvinceName = "New York"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.RegisformModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GeneralId")
                        .HasColumnType("int");

                    b.Property<int>("ShippingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneralId");

                    b.HasIndex("ShippingId");

                    b.ToTable("Regisforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GeneralId = 1,
                            ShippingId = 1
                        },
                        new
                        {
                            Id = 2,
                            GeneralId = 2,
                            ShippingId = 2
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.RegisterFrom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Test1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Test1");

                    b.ToTable("RegisterForms");
                });

            modelBuilder.Entity("ModelTest.Controllers.ShippingModel", b =>
                {
                    b.Property<int>("shipping_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipping_id"));

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("subDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shipping_id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Shippings");

                    b.HasData(
                        new
                        {
                            shipping_id = 1,
                            ProvinceId = 1,
                            subDistrict = "Wang Thonglang"
                        },
                        new
                        {
                            shipping_id = 2,
                            ProvinceId = 2,
                            subDistrict = "Mueang Chiang Mai"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.TestModel", b =>
                {
                    b.Property<string>("Test")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Test");

                    b.ToTable("TestModel");
                });

            modelBuilder.Entity("ModelTest.Controllers.ThaiProvince", b =>
                {
                    b.Property<int>("ThaiProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThaiProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("GeographyId")
                        .HasColumnType("int");

                    b.Property<string>("ThaiProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThaiProvinceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GeographyId");

                    b.ToTable("ThaiProvinces");

                    b.HasData(
                        new
                        {
                            ThaiProvinceId = 1,
                            CountryId = 1,
                            GeographyId = 1,
                            ThaiProvinceName = "เชียงใหม่"
                        },
                        new
                        {
                            ThaiProvinceId = 2,
                            CountryId = 1,
                            GeographyId = 2,
                            ThaiProvinceName = "กรุงเทพมหานคร"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.shopTypeModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("InduTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("shopType");
                });

            modelBuilder.Entity("SaleOrgModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("saleOrgCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saleOrgDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("saleOrgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SaleOrg");
                });

            modelBuilder.Entity("accountGroupModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("accGroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accGroupDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accGroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("accountGroup");
                });

            modelBuilder.Entity("ModelTest.Controllers.AddressModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.ProvinceModel", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.HasOne("ModelTest.Controllers.ThaiProvince", "ThaiProvince")
                        .WithMany()
                        .HasForeignKey("ThaiProvinceId");

                    b.Navigation("Country");

                    b.Navigation("Province");

                    b.Navigation("ThaiProvince");
                });

            modelBuilder.Entity("ModelTest.Controllers.GeneralModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.AddressModel", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.GeographyModel", "Geography")
                        .WithMany("Provinces")
                        .HasForeignKey("GeographyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Geography");
                });

            modelBuilder.Entity("ModelTest.Controllers.RegisformModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.GeneralModel", "General")
                        .WithMany()
                        .HasForeignKey("GeneralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.ShippingModel", "Shipping")
                        .WithMany()
                        .HasForeignKey("ShippingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("General");

                    b.Navigation("Shipping");
                });

            modelBuilder.Entity("ModelTest.Controllers.RegisterFrom", b =>
                {
                    b.HasOne("ModelTest.Controllers.TestModel", "Test")
                        .WithMany()
                        .HasForeignKey("Test1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("ModelTest.Controllers.ShippingModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.ProvinceModel", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ModelTest.Controllers.ThaiProvince", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany("ThaiProvinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.GeographyModel", "Geography")
                        .WithMany("ThaiProvinces")
                        .HasForeignKey("GeographyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Geography");
                });

            modelBuilder.Entity("ModelTest.Controllers.CountryModel", b =>
                {
                    b.Navigation("Provinces");

                    b.Navigation("ThaiProvinces");
                });

            modelBuilder.Entity("ModelTest.Controllers.GeographyModel", b =>
                {
                    b.Navigation("Provinces");

                    b.Navigation("ThaiProvinces");
                });
#pragma warning restore 612, 618
        }
    }
}
