// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace apiNet8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AddressModel", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            CountryId = 1,
                            ProvinceId = 1
                        },
                        new
                        {
                            AddressId = 2,
                            CountryId = 2,
                            ProvinceId = 2
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.CountryModel", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "Japan"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.CustomerModel", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneralId")
                        .HasColumnType("int");

                    b.Property<int>("shipping_id")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("GeneralId");

                    b.HasIndex("shipping_id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "สมชาย",
                            GeneralId = 1,
                            shipping_id = 1
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "สมหญิง",
                            GeneralId = 2,
                            shipping_id = 2
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.GeneralModel", b =>
                {
                    b.Property<int>("general_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("general_id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("generalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("general_id");

                    b.HasIndex("AddressId");

                    b.ToTable("Generals");

                    b.HasData(
                        new
                        {
                            general_id = 1,
                            AddressId = 1,
                            generalName = "General A"
                        },
                        new
                        {
                            general_id = 2,
                            AddressId = 2,
                            generalName = "General B"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            CountryId = 1,
                            ProvinceName = "Bangkok"
                        },
                        new
                        {
                            ProvinceId = 2,
                            CountryId = 2,
                            ProvinceName = "Tokyo"
                        });
                });

            modelBuilder.Entity("ModelTest.Controllers.ShippingModel", b =>
                {
                    b.Property<int>("shipping_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shipping_id"));

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("subDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("shipping_id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Shippings");

                    b.HasData(
                        new
                        {
                            shipping_id = 1,
                            ProvinceId = 1,
                            subDistrict = "บางรัก"
                        },
                        new
                        {
                            shipping_id = 2,
                            ProvinceId = 2,
                            subDistrict = "ห้วยขวาง"
                        });
                });

            modelBuilder.Entity("AddressModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.ProvinceModel", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ModelTest.Controllers.CustomerModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.GeneralModel", "General")
                        .WithMany()
                        .HasForeignKey("GeneralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelTest.Controllers.ShippingModel", "Shipping")
                        .WithMany()
                        .HasForeignKey("shipping_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("General");

                    b.Navigation("Shipping");
                });

            modelBuilder.Entity("ModelTest.Controllers.GeneralModel", b =>
                {
                    b.HasOne("AddressModel", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ModelTest.Controllers.ProvinceModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.CountryModel", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ModelTest.Controllers.ShippingModel", b =>
                {
                    b.HasOne("ModelTest.Controllers.ProvinceModel", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ModelTest.Controllers.CountryModel", b =>
                {
                    b.Navigation("Provinces");
                });
#pragma warning restore 612, 618
        }
    }
}
