// Re-export enums matching Prisma schema for use across the application

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
}

export enum RoleCode {
  CUSTOMER = 'CUSTOMER',
  BANK_OFFICER = 'BANK_OFFICER',
  APPROVER = 'APPROVER',
  ADMIN = 'ADMIN',
}

export enum ApplicationType {
  PERSONAL_LOAN = 'PERSONAL_LOAN',
  CORPORATE_LOAN = 'CORPORATE_LOAN',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  DOCUMENT_CHECK = 'DOCUMENT_CHECK',
  CREDIT_ANALYSIS = 'CREDIT_ANALYSIS',
  APPROVAL = 'APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NEED_MORE_INFO = 'NEED_MORE_INFO',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
  DISBURSED = 'DISBURSED',
  CANCELLED = 'CANCELLED',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum MaritalStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
}

export enum EmploymentType {
  EMPLOYED = 'EMPLOYED',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  RETIRED = 'RETIRED',
  UNEMPLOYED = 'UNEMPLOYED',
}

export enum DocumentType {
  NATIONAL_ID = 'NATIONAL_ID',
  PASSPORT = 'PASSPORT',
  INCOME_STATEMENT = 'INCOME_STATEMENT',
  BANK_STATEMENT = 'BANK_STATEMENT',
  TAX_RETURN = 'TAX_RETURN',
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
  FINANCIAL_STATEMENT = 'FINANCIAL_STATEMENT',
  COLLATERAL_DOCS = 'COLLATERAL_DOCS',
  CREDIT_REPORT = 'CREDIT_REPORT',
  GUARANTOR_ID = 'GUARANTOR_ID',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum ApprovalDecision {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NEED_MORE_INFO = 'NEED_MORE_INFO',
  ESCALATED = 'ESCALATED',
}

export enum RiskGrade {
  A_PLUS = 'A_PLUS',
  A = 'A',
  B_PLUS = 'B_PLUS',
  B = 'B',
  C = 'C',
  D = 'D',
}

export enum AddressType {
  HOME = 'HOME',
  WORK = 'WORK',
  MAILING = 'MAILING',
  REGISTERED = 'REGISTERED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  DOCUMENT_UPLOAD = 'DOCUMENT_UPLOAD',
  DOCUMENT_VERIFY = 'DOCUMENT_VERIFY',
  CREDIT_ANALYSIS = 'CREDIT_ANALYSIS',
  APPROVAL_DECISION = 'APPROVAL_DECISION',
  DATA_ACCESS = 'DATA_ACCESS',
}
