/**
 * CreditAccountApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisterListItem } from './registerListItem';


export interface GetAllRegistersResponse { 
    items?: Array<RegisterListItem> | null;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    readonly totalPages?: number;
}

