/**
 * CreditAccountApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisterListItem } from './registerListItem';


export interface GetAllRegistersResponse { 
    items?: Array<RegisterListItem>;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
}

