/**
 * CreditAccountApi | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetRegisterResponse { 
    registerId?: number;
    createdAt?: string | null;
    generalName1?: string | null;
    generalName2?: string | null;
    generalTax?: string | null;
    generalBranch?: string | null;
    generalTel?: string | null;
    generalFax?: string | null;
    generalEmail?: string | null;
    generalLine?: string | null;
    addrLine1?: string | null;
    addrLine2?: string | null;
    subDistrict?: string | null;
    district?: string | null;
    province?: string | null;
    postalCode?: string | null;
    country?: string | null;
    creditLimit?: number | null;
    estimatedPurchase?: number | null;
    timeRequired?: string | null;
    companyCertificate?: boolean;
    copyOfPp20?: boolean;
    copyOfCoRegis?: boolean;
    copyOfIdCard?: boolean;
    companyLocationMap?: boolean;
    otherSpecify?: string | null;
    custsignFirstname?: string | null;
    custsignLastname?: string | null;
    custsignTel?: string | null;
    custsignEmail?: string | null;
    custsignLine?: string | null;
    businessType?: string | null;
    industryType?: string | null;
    shopType?: string | null;
    termOfPay?: string | null;
    paymentMethod?: string | null;
    currency?: string | null;
    incoterms?: string | null;
}

