/**
 * CreditAccountApi, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterListItem { 
    registerId?: number;
    createdAt?: string | null;
    generalName1?: string | null;
    generalTax?: string | null;
    province?: string | null;
    creditLimit?: number | null;
}

